#!/bin/sh
a=`grep $1 ifup.ini`
if [ "$a" = "" ] ; then
  /sbin/ifconfig $1 up
else
  ip=`echo $a | cut -f2 -d" "`
  mask=`echo $a | cut -f3 -d" "`
  if [ "$ip" = "bridge" ] ; then
    ifconfig $1 up
    ( sleep 5 && ./bridge $1 $mask) &
  else
    /sbin/ifconfig $1 $ip netmask $mask up
  fi
fi
