# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ConfigurationPages/Form_QemuPage.ui'
#
# Created: Fri Jul  5 13:39:31 2013
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_QemuPage(object):
    def setupUi(self, QemuPage):
        QemuPage.setObjectName(_fromUtf8("QemuPage"))
        QemuPage.resize(419, 453)
        QemuPage.setWindowTitle(QtGui.QApplication.translate("QemuPage", "Qemu configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout = QtGui.QGridLayout(QemuPage)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(QemuPage)
        self.label.setText(QtGui.QApplication.translate("QemuPage", "Qemu Flavor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBoxFlavor = QtGui.QComboBox(QemuPage)
        self.comboBoxFlavor.setObjectName(_fromUtf8("comboBoxFlavor"))
        self.comboBoxFlavor.addItem(_fromUtf8(""))
        self.comboBoxFlavor.setItemText(0, QtGui.QApplication.translate("QemuPage", "Default", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFlavor.addItem(_fromUtf8(""))
        self.comboBoxFlavor.setItemText(1, QtGui.QApplication.translate("QemuPage", "-i386", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFlavor.addItem(_fromUtf8(""))
        self.comboBoxFlavor.setItemText(2, QtGui.QApplication.translate("QemuPage", "-x86_64", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFlavor.addItem(_fromUtf8(""))
        self.comboBoxFlavor.setItemText(3, QtGui.QApplication.translate("QemuPage", "-sparc", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxFlavor.addItem(_fromUtf8(""))
        self.comboBoxFlavor.setItemText(4, QtGui.QApplication.translate("QemuPage", "-arm", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.comboBoxFlavor, 0, 1, 1, 2)
        self.label_17 = QtGui.QLabel(QemuPage)
        self.label_17.setText(QtGui.QApplication.translate("QemuPage", "Qemu Image:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout.addWidget(self.label_17, 1, 0, 1, 1)
        self.lineEditImage = QtGui.QLineEdit(QemuPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditImage.sizePolicy().hasHeightForWidth())
        self.lineEditImage.setSizePolicy(sizePolicy)
        self.lineEditImage.setObjectName(_fromUtf8("lineEditImage"))
        self.gridLayout.addWidget(self.lineEditImage, 1, 1, 1, 1)
        self.pushButtonImageBrowser = QtGui.QPushButton(QemuPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonImageBrowser.sizePolicy().hasHeightForWidth())
        self.pushButtonImageBrowser.setSizePolicy(sizePolicy)
        self.pushButtonImageBrowser.setMaximumSize(QtCore.QSize(31, 27))
        self.pushButtonImageBrowser.setText(QtGui.QApplication.translate("QemuPage", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonImageBrowser.setObjectName(_fromUtf8("pushButtonImageBrowser"))
        self.gridLayout.addWidget(self.pushButtonImageBrowser, 1, 2, 1, 1)
        self.label_24 = QtGui.QLabel(QemuPage)
        self.label_24.setText(QtGui.QApplication.translate("QemuPage", "RAM:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout.addWidget(self.label_24, 2, 0, 1, 1)
        self.spinBoxRamSize = QtGui.QSpinBox(QemuPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxRamSize.sizePolicy().hasHeightForWidth())
        self.spinBoxRamSize.setSizePolicy(sizePolicy)
        self.spinBoxRamSize.setSuffix(QtGui.QApplication.translate("QemuPage", " MiB", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBoxRamSize.setMaximum(100000)
        self.spinBoxRamSize.setSingleStep(4)
        self.spinBoxRamSize.setProperty("value", 128)
        self.spinBoxRamSize.setObjectName(_fromUtf8("spinBoxRamSize"))
        self.gridLayout.addWidget(self.spinBoxRamSize, 2, 1, 1, 2)
        self.label_37 = QtGui.QLabel(QemuPage)
        self.label_37.setText(QtGui.QApplication.translate("QemuPage", "Number of NICs:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout.addWidget(self.label_37, 3, 0, 1, 1)
        self.spinBoxNics = QtGui.QSpinBox(QemuPage)
        self.spinBoxNics.setMinimum(0)
        self.spinBoxNics.setMaximum(100000)
        self.spinBoxNics.setSingleStep(1)
        self.spinBoxNics.setProperty("value", 6)
        self.spinBoxNics.setObjectName(_fromUtf8("spinBoxNics"))
        self.gridLayout.addWidget(self.spinBoxNics, 3, 1, 1, 2)
        self.label_26 = QtGui.QLabel(QemuPage)
        self.label_26.setText(QtGui.QApplication.translate("QemuPage", "NIC model:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout.addWidget(self.label_26, 4, 0, 1, 1)
        self.comboBoxNIC = QtGui.QComboBox(QemuPage)
        self.comboBoxNIC.setEnabled(True)
        self.comboBoxNIC.setObjectName(_fromUtf8("comboBoxNIC"))
        self.comboBoxNIC.addItem(_fromUtf8(""))
        self.comboBoxNIC.setItemText(0, QtGui.QApplication.translate("QemuPage", "rtl8139", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxNIC.addItem(_fromUtf8(""))
        self.comboBoxNIC.setItemText(1, QtGui.QApplication.translate("QemuPage", "ne2k_pci", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxNIC.addItem(_fromUtf8(""))
        self.comboBoxNIC.setItemText(2, QtGui.QApplication.translate("QemuPage", "i82551", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxNIC.addItem(_fromUtf8(""))
        self.comboBoxNIC.setItemText(3, QtGui.QApplication.translate("QemuPage", "i82557b", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxNIC.addItem(_fromUtf8(""))
        self.comboBoxNIC.setItemText(4, QtGui.QApplication.translate("QemuPage", "i82559er", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxNIC.addItem(_fromUtf8(""))
        self.comboBoxNIC.setItemText(5, QtGui.QApplication.translate("QemuPage", "e1000", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxNIC.addItem(_fromUtf8(""))
        self.comboBoxNIC.setItemText(6, QtGui.QApplication.translate("QemuPage", "pcnet", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxNIC.addItem(_fromUtf8(""))
        self.comboBoxNIC.setItemText(7, QtGui.QApplication.translate("QemuPage", "virtio", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxNIC.addItem(_fromUtf8(""))
        self.comboBoxNIC.setItemText(8, QtGui.QApplication.translate("QemuPage", "lance", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxNIC.addItem(_fromUtf8(""))
        self.comboBoxNIC.setItemText(9, QtGui.QApplication.translate("QemuPage", "virtio-net-pci", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBoxNIC.addItem(_fromUtf8(""))
        self.comboBoxNIC.setItemText(10, QtGui.QApplication.translate("QemuPage", "smc91c111", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout.addWidget(self.comboBoxNIC, 4, 1, 1, 2)
        self.label_8 = QtGui.QLabel(QemuPage)
        self.label_8.setText(QtGui.QApplication.translate("QemuPage", "Qemu Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.lineEditOptions = QtGui.QLineEdit(QemuPage)
        self.lineEditOptions.setEnabled(True)
        self.lineEditOptions.setObjectName(_fromUtf8("lineEditOptions"))
        self.gridLayout.addWidget(self.lineEditOptions, 5, 1, 1, 2)
        self.checkBoxKVM = QtGui.QCheckBox(QemuPage)
        self.checkBoxKVM.setEnabled(True)
        self.checkBoxKVM.setText(QtGui.QApplication.translate("QemuPage", "Use KVM (Linux hosts only)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxKVM.setObjectName(_fromUtf8("checkBoxKVM"))
        self.gridLayout.addWidget(self.checkBoxKVM, 6, 0, 1, 2)
        self.checkBoxUserMod = QtGui.QCheckBox(QemuPage)
        self.checkBoxUserMod.setText(QtGui.QApplication.translate("QemuPage", "Add user network backend", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxUserMod.setChecked(False)
        self.checkBoxUserMod.setTristate(False)
        self.checkBoxUserMod.setObjectName(_fromUtf8("checkBoxUserMod"))
        self.gridLayout.addWidget(self.checkBoxUserMod, 7, 0, 1, 3)
        self.checkBoxMonitor = QtGui.QCheckBox(QemuPage)
        self.checkBoxMonitor.setText(QtGui.QApplication.translate("QemuPage", "Monitor mode (pause and resume)", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxMonitor.setObjectName(_fromUtf8("checkBoxMonitor"))
        self.gridLayout.addWidget(self.checkBoxMonitor, 8, 0, 1, 3)
        spacerItem = QtGui.QSpacerItem(20, 281, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 1, 1, 1)

        self.retranslateUi(QemuPage)
        self.comboBoxNIC.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(QemuPage)

    def retranslateUi(self, QemuPage):
        pass

