# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ConfigurationPages/Form_PreferencesQemu.ui'
#
# Created: Mon Apr 11 15:55:34 2011
#      by: PyQt4 UI code generator 4.8.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_PreferencesQemu(object):
    def setupUi(self, PreferencesQemu):
        PreferencesQemu.setObjectName(_fromUtf8("PreferencesQemu"))
        PreferencesQemu.resize(526, 563)
        self.verticalLayout_17 = QtGui.QVBoxLayout(PreferencesQemu)
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.tabWidget = QtGui.QTabWidget(PreferencesQemu)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.P = QtGui.QGroupBox(self.tab)
        self.P.setObjectName(_fromUtf8("P"))
        self.gridLayout_7 = QtGui.QGridLayout(self.P)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_3 = QtGui.QLabel(self.P)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEditQemuwrapperPath = QtGui.QLineEdit(self.P)
        self.lineEditQemuwrapperPath.setObjectName(_fromUtf8("lineEditQemuwrapperPath"))
        self.gridLayout_7.addWidget(self.lineEditQemuwrapperPath, 0, 1, 1, 5)
        self.QemuwrapperPath_browser = QtGui.QToolButton(self.P)
        self.QemuwrapperPath_browser.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.QemuwrapperPath_browser.setObjectName(_fromUtf8("QemuwrapperPath_browser"))
        self.gridLayout_7.addWidget(self.QemuwrapperPath_browser, 0, 6, 1, 1)
        self.label_2 = QtGui.QLabel(self.P)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEditQemuwrapperWorkdir = QtGui.QLineEdit(self.P)
        self.lineEditQemuwrapperWorkdir.setObjectName(_fromUtf8("lineEditQemuwrapperWorkdir"))
        self.gridLayout_7.addWidget(self.lineEditQemuwrapperWorkdir, 1, 1, 1, 5)
        self.QemuwrapperWorkdir_browser = QtGui.QToolButton(self.P)
        self.QemuwrapperWorkdir_browser.setObjectName(_fromUtf8("QemuwrapperWorkdir_browser"))
        self.gridLayout_7.addWidget(self.QemuwrapperWorkdir_browser, 1, 6, 1, 1)
        self.label_16 = QtGui.QLabel(self.P)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 2, 0, 1, 1)
        self.lineEditQemuPath = QtGui.QLineEdit(self.P)
        self.lineEditQemuPath.setObjectName(_fromUtf8("lineEditQemuPath"))
        self.gridLayout_7.addWidget(self.lineEditQemuPath, 2, 1, 1, 5)
        self.QemuPath_browser = QtGui.QToolButton(self.P)
        self.QemuPath_browser.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.QemuPath_browser.setObjectName(_fromUtf8("QemuPath_browser"))
        self.gridLayout_7.addWidget(self.QemuPath_browser, 2, 6, 1, 1)
        self.label_17 = QtGui.QLabel(self.P)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 3, 0, 1, 1)
        self.lineEditQemuImgPath = QtGui.QLineEdit(self.P)
        self.lineEditQemuImgPath.setObjectName(_fromUtf8("lineEditQemuImgPath"))
        self.gridLayout_7.addWidget(self.lineEditQemuImgPath, 3, 1, 1, 5)
        self.QemuImgPath_browser = QtGui.QToolButton(self.P)
        self.QemuImgPath_browser.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.QemuImgPath_browser.setObjectName(_fromUtf8("QemuImgPath_browser"))
        self.gridLayout_7.addWidget(self.QemuImgPath_browser, 3, 6, 1, 1)
        self.label_6 = QtGui.QLabel(self.P)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_7.addWidget(self.label_6, 4, 0, 1, 1)
        self.comboBoxBinding = QtGui.QComboBox(self.P)
        self.comboBoxBinding.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToMinimumContentsLength)
        self.comboBoxBinding.setObjectName(_fromUtf8("comboBoxBinding"))
        self.gridLayout_7.addWidget(self.comboBoxBinding, 4, 1, 1, 6)
        self.label_35 = QtGui.QLabel(self.P)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_7.addWidget(self.label_35, 5, 0, 1, 1)
        self.port = QtGui.QSpinBox(self.P)
        self.port.setEnabled(True)
        self.port.setMinimum(1)
        self.port.setMaximum(65535)
        self.port.setObjectName(_fromUtf8("port"))
        self.gridLayout_7.addWidget(self.port, 5, 1, 1, 6)
        self.label_31 = QtGui.QLabel(self.P)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_7.addWidget(self.label_31, 6, 0, 1, 1)
        self.baseUDP = QtGui.QSpinBox(self.P)
        self.baseUDP.setEnabled(True)
        self.baseUDP.setMinimum(1)
        self.baseUDP.setMaximum(65535)
        self.baseUDP.setObjectName(_fromUtf8("baseUDP"))
        self.gridLayout_7.addWidget(self.baseUDP, 6, 1, 1, 6)
        self.label_30 = QtGui.QLabel(self.P)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_7.addWidget(self.label_30, 7, 0, 1, 1)
        self.baseConsole = QtGui.QSpinBox(self.P)
        self.baseConsole.setEnabled(True)
        self.baseConsole.setMinimum(1)
        self.baseConsole.setMaximum(65535)
        self.baseConsole.setObjectName(_fromUtf8("baseConsole"))
        self.gridLayout_7.addWidget(self.baseConsole, 7, 1, 1, 6)
        self.checkBoxEnableQemuManager = QtGui.QCheckBox(self.P)
        self.checkBoxEnableQemuManager.setChecked(True)
        self.checkBoxEnableQemuManager.setObjectName(_fromUtf8("checkBoxEnableQemuManager"))
        self.gridLayout_7.addWidget(self.checkBoxEnableQemuManager, 8, 0, 1, 3)
        self.checkBoxQemuManagerImport = QtGui.QCheckBox(self.P)
        self.checkBoxQemuManagerImport.setChecked(True)
        self.checkBoxQemuManagerImport.setObjectName(_fromUtf8("checkBoxQemuManagerImport"))
        self.gridLayout_7.addWidget(self.checkBoxQemuManagerImport, 9, 0, 1, 4)
        self.label_5 = QtGui.QLabel(self.P)
        self.label_5.setEnabled(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_7.addWidget(self.label_5, 10, 0, 1, 2)
        self.lineEditHostExternalQemu = QtGui.QLineEdit(self.P)
        self.lineEditHostExternalQemu.setObjectName(_fromUtf8("lineEditHostExternalQemu"))
        self.gridLayout_7.addWidget(self.lineEditHostExternalQemu, 10, 2, 1, 2)
        self.pushButtonAddExternalQemuwrapper = QtGui.QPushButton(self.P)
        self.pushButtonAddExternalQemuwrapper.setObjectName(_fromUtf8("pushButtonAddExternalQemuwrapper"))
        self.gridLayout_7.addWidget(self.pushButtonAddExternalQemuwrapper, 10, 4, 1, 1)
        self.pushButtonDeleteExternalQemuwrapper = QtGui.QPushButton(self.P)
        self.pushButtonDeleteExternalQemuwrapper.setObjectName(_fromUtf8("pushButtonDeleteExternalQemuwrapper"))
        self.gridLayout_7.addWidget(self.pushButtonDeleteExternalQemuwrapper, 10, 5, 1, 2)
        self.label_36 = QtGui.QLabel(self.P)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_7.addWidget(self.label_36, 11, 0, 1, 3)
        self.comboBoxExternalQemuwrappers = QtGui.QComboBox(self.P)
        self.comboBoxExternalQemuwrappers.setObjectName(_fromUtf8("comboBoxExternalQemuwrappers"))
        self.gridLayout_7.addWidget(self.comboBoxExternalQemuwrappers, 11, 3, 1, 4)
        self.verticalLayout_2.addWidget(self.P)
        self.hboxlayout = QtGui.QHBoxLayout()
        self.hboxlayout.setObjectName(_fromUtf8("hboxlayout"))
        self.pushButtonTestQemu = QtGui.QPushButton(self.tab)
        self.pushButtonTestQemu.setObjectName(_fromUtf8("pushButtonTestQemu"))
        self.hboxlayout.addWidget(self.pushButtonTestQemu)
        self.labelQemuStatus = QtGui.QLabel(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelQemuStatus.sizePolicy().hasHeightForWidth())
        self.labelQemuStatus.setSizePolicy(sizePolicy)
        self.labelQemuStatus.setText(_fromUtf8(""))
        self.labelQemuStatus.setObjectName(_fromUtf8("labelQemuStatus"))
        self.hboxlayout.addWidget(self.labelQemuStatus)
        self.verticalLayout_2.addLayout(self.hboxlayout)
        spacerItem = QtGui.QSpacerItem(20, 24, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.scrollArea = QtGui.QScrollArea(self.tab_4)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget(self.scrollArea)
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 452, 480))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_14 = QtGui.QLabel(self.groupBox)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout.addWidget(self.label_14, 0, 0, 1, 1)
        self.NameQemuImage = QtGui.QLineEdit(self.groupBox)
        self.NameQemuImage.setObjectName(_fromUtf8("NameQemuImage"))
        self.gridLayout.addWidget(self.NameQemuImage, 0, 1, 1, 2)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setEnabled(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.QemuImage = QtGui.QLineEdit(self.groupBox)
        self.QemuImage.setObjectName(_fromUtf8("QemuImage"))
        self.gridLayout.addWidget(self.QemuImage, 1, 1, 1, 1)
        self.QemuImage_Browser = QtGui.QToolButton(self.groupBox)
        self.QemuImage_Browser.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.QemuImage_Browser.setObjectName(_fromUtf8("QemuImage_Browser"))
        self.gridLayout.addWidget(self.QemuImage_Browser, 1, 2, 1, 1)
        self.label_20 = QtGui.QLabel(self.groupBox)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout.addWidget(self.label_20, 2, 0, 1, 1)
        self.QemuMemory = QtGui.QSpinBox(self.groupBox)
        self.QemuMemory.setMinimum(1)
        self.QemuMemory.setMaximum(100000)
        self.QemuMemory.setSingleStep(16)
        self.QemuMemory.setProperty(_fromUtf8("value"), 128)
        self.QemuMemory.setObjectName(_fromUtf8("QemuMemory"))
        self.gridLayout.addWidget(self.QemuMemory, 2, 1, 1, 2)
        self.label_37 = QtGui.QLabel(self.groupBox)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout.addWidget(self.label_37, 3, 0, 1, 1)
        self.QemuNICNb = QtGui.QSpinBox(self.groupBox)
        self.QemuNICNb.setMinimum(0)
        self.QemuNICNb.setMaximum(100000)
        self.QemuNICNb.setSingleStep(1)
        self.QemuNICNb.setProperty(_fromUtf8("value"), 6)
        self.QemuNICNb.setObjectName(_fromUtf8("QemuNICNb"))
        self.gridLayout.addWidget(self.QemuNICNb, 3, 1, 1, 2)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.QemuNIC = QtGui.QComboBox(self.groupBox)
        self.QemuNIC.setObjectName(_fromUtf8("QemuNIC"))
        self.QemuNIC.addItem(_fromUtf8(""))
        self.QemuNIC.addItem(_fromUtf8(""))
        self.QemuNIC.addItem(_fromUtf8(""))
        self.QemuNIC.addItem(_fromUtf8(""))
        self.QemuNIC.addItem(_fromUtf8(""))
        self.QemuNIC.addItem(_fromUtf8(""))
        self.QemuNIC.addItem(_fromUtf8(""))
        self.QemuNIC.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.QemuNIC, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.QemuOptions = QtGui.QLineEdit(self.groupBox)
        self.QemuOptions.setObjectName(_fromUtf8("QemuOptions"))
        self.gridLayout.addWidget(self.QemuOptions, 5, 1, 1, 2)
        self.QemucheckBoxKqemu = QtGui.QCheckBox(self.groupBox)
        self.QemucheckBoxKqemu.setObjectName(_fromUtf8("QemucheckBoxKqemu"))
        self.gridLayout.addWidget(self.QemucheckBoxKqemu, 6, 0, 1, 1)
        self.QemucheckBoxKVM = QtGui.QCheckBox(self.groupBox)
        self.QemucheckBoxKVM.setObjectName(_fromUtf8("QemucheckBoxKVM"))
        self.gridLayout.addWidget(self.QemucheckBoxKVM, 6, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.SaveQemuImage = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.SaveQemuImage.setObjectName(_fromUtf8("SaveQemuImage"))
        self.horizontalLayout.addWidget(self.SaveQemuImage)
        self.DeleteQemuImage = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.DeleteQemuImage.setObjectName(_fromUtf8("DeleteQemuImage"))
        self.horizontalLayout.addWidget(self.DeleteQemuImage)
        spacerItem1 = QtGui.QSpacerItem(217, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.groupBox_8 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.treeWidgetQemuImages = QtGui.QTreeWidget(self.groupBox_8)
        self.treeWidgetQemuImages.setObjectName(_fromUtf8("treeWidgetQemuImages"))
        self.verticalLayout_5.addWidget(self.treeWidgetQemuImages)
        self.verticalLayout.addWidget(self.groupBox_8)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_7.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab_5)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_5)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget(self.scrollArea_2)
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 437, 554))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.groupBox_6 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_38 = QtGui.QLabel(self.groupBox_6)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_6.addWidget(self.label_38, 0, 0, 1, 1)
        self.NamePIXImage = QtGui.QLineEdit(self.groupBox_6)
        self.NamePIXImage.setObjectName(_fromUtf8("NamePIXImage"))
        self.gridLayout_6.addWidget(self.NamePIXImage, 0, 1, 1, 2)
        self.label_23 = QtGui.QLabel(self.groupBox_6)
        self.label_23.setEnabled(True)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_6.addWidget(self.label_23, 1, 0, 1, 1)
        self.PIXImage = QtGui.QLineEdit(self.groupBox_6)
        self.PIXImage.setEnabled(True)
        self.PIXImage.setObjectName(_fromUtf8("PIXImage"))
        self.gridLayout_6.addWidget(self.PIXImage, 1, 1, 1, 1)
        self.PIXImage_Browser = QtGui.QToolButton(self.groupBox_6)
        self.PIXImage_Browser.setEnabled(True)
        self.PIXImage_Browser.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.PIXImage_Browser.setObjectName(_fromUtf8("PIXImage_Browser"))
        self.gridLayout_6.addWidget(self.PIXImage_Browser, 1, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_6)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_6.addWidget(self.label_29, 2, 0, 1, 1)
        self.PIXMemory = QtGui.QSpinBox(self.groupBox_6)
        self.PIXMemory.setEnabled(True)
        self.PIXMemory.setMinimum(1)
        self.PIXMemory.setMaximum(100000)
        self.PIXMemory.setSingleStep(16)
        self.PIXMemory.setProperty(_fromUtf8("value"), 128)
        self.PIXMemory.setObjectName(_fromUtf8("PIXMemory"))
        self.gridLayout_6.addWidget(self.PIXMemory, 2, 1, 1, 2)
        self.label_39 = QtGui.QLabel(self.groupBox_6)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_6.addWidget(self.label_39, 3, 0, 1, 1)
        self.PIXNICNb = QtGui.QSpinBox(self.groupBox_6)
        self.PIXNICNb.setMinimum(0)
        self.PIXNICNb.setMaximum(100000)
        self.PIXNICNb.setSingleStep(1)
        self.PIXNICNb.setProperty(_fromUtf8("value"), 6)
        self.PIXNICNb.setObjectName(_fromUtf8("PIXNICNb"))
        self.gridLayout_6.addWidget(self.PIXNICNb, 3, 1, 1, 2)
        self.label_26 = QtGui.QLabel(self.groupBox_6)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_6.addWidget(self.label_26, 4, 0, 1, 1)
        self.PIXNIC = QtGui.QComboBox(self.groupBox_6)
        self.PIXNIC.setEnabled(True)
        self.PIXNIC.setObjectName(_fromUtf8("PIXNIC"))
        self.PIXNIC.addItem(_fromUtf8(""))
        self.PIXNIC.addItem(_fromUtf8(""))
        self.PIXNIC.addItem(_fromUtf8(""))
        self.PIXNIC.addItem(_fromUtf8(""))
        self.PIXNIC.addItem(_fromUtf8(""))
        self.PIXNIC.addItem(_fromUtf8(""))
        self.PIXNIC.addItem(_fromUtf8(""))
        self.PIXNIC.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.PIXNIC, 4, 1, 1, 2)
        self.label_8 = QtGui.QLabel(self.groupBox_6)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 5, 0, 1, 1)
        self.PIXOptions = QtGui.QLineEdit(self.groupBox_6)
        self.PIXOptions.setEnabled(True)
        self.PIXOptions.setObjectName(_fromUtf8("PIXOptions"))
        self.gridLayout_6.addWidget(self.PIXOptions, 5, 1, 1, 2)
        self.PIXcheckBoxKqemu = QtGui.QCheckBox(self.groupBox_6)
        self.PIXcheckBoxKqemu.setEnabled(True)
        self.PIXcheckBoxKqemu.setObjectName(_fromUtf8("PIXcheckBoxKqemu"))
        self.gridLayout_6.addWidget(self.PIXcheckBoxKqemu, 6, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_6)
        self.groupBox_7 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_24 = QtGui.QLabel(self.groupBox_7)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 0, 0, 1, 1)
        self.PIXKey = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PIXKey.sizePolicy().hasHeightForWidth())
        self.PIXKey.setSizePolicy(sizePolicy)
        self.PIXKey.setText(_fromUtf8(""))
        self.PIXKey.setObjectName(_fromUtf8("PIXKey"))
        self.gridLayout_5.addWidget(self.PIXKey, 0, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_7)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 1, 0, 1, 1)
        self.PIXSerial = QtGui.QLineEdit(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PIXSerial.sizePolicy().hasHeightForWidth())
        self.PIXSerial.setSizePolicy(sizePolicy)
        self.PIXSerial.setText(_fromUtf8(""))
        self.PIXSerial.setObjectName(_fromUtf8("PIXSerial"))
        self.gridLayout_5.addWidget(self.PIXSerial, 1, 1, 1, 1)
        self.verticalLayout_9.addWidget(self.groupBox_7)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.SavePIXImage = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.SavePIXImage.setObjectName(_fromUtf8("SavePIXImage"))
        self.horizontalLayout_2.addWidget(self.SavePIXImage)
        self.DeletePIXImage = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        self.DeletePIXImage.setObjectName(_fromUtf8("DeletePIXImage"))
        self.horizontalLayout_2.addWidget(self.DeletePIXImage)
        spacerItem3 = QtGui.QSpacerItem(217, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_2)
        self.groupBox_10 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.treeWidgetPIXImages = QtGui.QTreeWidget(self.groupBox_10)
        self.treeWidgetPIXImages.setObjectName(_fromUtf8("treeWidgetPIXImages"))
        self.verticalLayout_6.addWidget(self.treeWidgetPIXImages)
        self.verticalLayout_9.addWidget(self.groupBox_10)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_10.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab_3)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.scrollArea_3 = QtGui.QScrollArea(self.tab_3)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget(self.scrollArea_3)
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 452, 480))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_40 = QtGui.QLabel(self.groupBox_5)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_2.addWidget(self.label_40, 0, 0, 1, 1)
        self.NameJunOSImage = QtGui.QLineEdit(self.groupBox_5)
        self.NameJunOSImage.setObjectName(_fromUtf8("NameJunOSImage"))
        self.gridLayout_2.addWidget(self.NameJunOSImage, 0, 1, 1, 2)
        self.label_7 = QtGui.QLabel(self.groupBox_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.JunOSImage = QtGui.QLineEdit(self.groupBox_5)
        self.JunOSImage.setEnabled(True)
        self.JunOSImage.setObjectName(_fromUtf8("JunOSImage"))
        self.gridLayout_2.addWidget(self.JunOSImage, 1, 1, 1, 1)
        self.JunOSImage_Browser = QtGui.QToolButton(self.groupBox_5)
        self.JunOSImage_Browser.setEnabled(True)
        self.JunOSImage_Browser.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.JunOSImage_Browser.setObjectName(_fromUtf8("JunOSImage_Browser"))
        self.gridLayout_2.addWidget(self.JunOSImage_Browser, 1, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_5)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_2.addWidget(self.label_21, 2, 0, 1, 1)
        self.JunOSMemory = QtGui.QSpinBox(self.groupBox_5)
        self.JunOSMemory.setEnabled(True)
        self.JunOSMemory.setMinimum(1)
        self.JunOSMemory.setMaximum(100000)
        self.JunOSMemory.setSingleStep(16)
        self.JunOSMemory.setProperty(_fromUtf8("value"), 96)
        self.JunOSMemory.setObjectName(_fromUtf8("JunOSMemory"))
        self.gridLayout_2.addWidget(self.JunOSMemory, 2, 1, 1, 2)
        self.label_41 = QtGui.QLabel(self.groupBox_5)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_2.addWidget(self.label_41, 3, 0, 1, 1)
        self.JunOSNICNb = QtGui.QSpinBox(self.groupBox_5)
        self.JunOSNICNb.setMinimum(0)
        self.JunOSNICNb.setMaximum(100000)
        self.JunOSNICNb.setSingleStep(1)
        self.JunOSNICNb.setProperty(_fromUtf8("value"), 6)
        self.JunOSNICNb.setObjectName(_fromUtf8("JunOSNICNb"))
        self.gridLayout_2.addWidget(self.JunOSNICNb, 3, 1, 1, 2)
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 4, 0, 1, 1)
        self.JunOSNIC = QtGui.QComboBox(self.groupBox_5)
        self.JunOSNIC.setEnabled(True)
        self.JunOSNIC.setObjectName(_fromUtf8("JunOSNIC"))
        self.JunOSNIC.addItem(_fromUtf8(""))
        self.JunOSNIC.addItem(_fromUtf8(""))
        self.JunOSNIC.addItem(_fromUtf8(""))
        self.JunOSNIC.addItem(_fromUtf8(""))
        self.JunOSNIC.addItem(_fromUtf8(""))
        self.JunOSNIC.addItem(_fromUtf8(""))
        self.JunOSNIC.addItem(_fromUtf8(""))
        self.JunOSNIC.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.JunOSNIC, 4, 1, 1, 2)
        self.label_9 = QtGui.QLabel(self.groupBox_5)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 5, 0, 1, 1)
        self.JunOSOptions = QtGui.QLineEdit(self.groupBox_5)
        self.JunOSOptions.setEnabled(True)
        self.JunOSOptions.setObjectName(_fromUtf8("JunOSOptions"))
        self.gridLayout_2.addWidget(self.JunOSOptions, 5, 1, 1, 2)
        self.JunOScheckBoxKqemu = QtGui.QCheckBox(self.groupBox_5)
        self.JunOScheckBoxKqemu.setEnabled(True)
        self.JunOScheckBoxKqemu.setObjectName(_fromUtf8("JunOScheckBoxKqemu"))
        self.gridLayout_2.addWidget(self.JunOScheckBoxKqemu, 6, 0, 1, 1)
        self.JunOScheckBoxKVM = QtGui.QCheckBox(self.groupBox_5)
        self.JunOScheckBoxKVM.setEnabled(True)
        self.JunOScheckBoxKVM.setObjectName(_fromUtf8("JunOScheckBoxKVM"))
        self.gridLayout_2.addWidget(self.JunOScheckBoxKVM, 7, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.SaveJunOSImage = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.SaveJunOSImage.setObjectName(_fromUtf8("SaveJunOSImage"))
        self.horizontalLayout_3.addWidget(self.SaveJunOSImage)
        self.DeleteJunOSImage = QtGui.QPushButton(self.scrollAreaWidgetContents_3)
        self.DeleteJunOSImage.setObjectName(_fromUtf8("DeleteJunOSImage"))
        self.horizontalLayout_3.addWidget(self.DeleteJunOSImage)
        spacerItem4 = QtGui.QSpacerItem(217, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.groupBox_11 = QtGui.QGroupBox(self.scrollAreaWidgetContents_3)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.treeWidgetJunOSImages = QtGui.QTreeWidget(self.groupBox_11)
        self.treeWidgetJunOSImages.setObjectName(_fromUtf8("treeWidgetJunOSImages"))
        self.verticalLayout_11.addWidget(self.treeWidgetJunOSImages)
        self.verticalLayout_4.addWidget(self.groupBox_11)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_12.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.scrollArea_4 = QtGui.QScrollArea(self.tab_2)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName(_fromUtf8("scrollArea_4"))
        self.scrollAreaWidgetContents_4 = QtGui.QWidget(self.scrollArea_4)
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 437, 579))
        self.scrollAreaWidgetContents_4.setObjectName(_fromUtf8("scrollAreaWidgetContents_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_3 = QtGui.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_42 = QtGui.QLabel(self.groupBox_3)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_3.addWidget(self.label_42, 0, 0, 1, 1)
        self.NameASAImage = QtGui.QLineEdit(self.groupBox_3)
        self.NameASAImage.setObjectName(_fromUtf8("NameASAImage"))
        self.gridLayout_3.addWidget(self.NameASAImage, 0, 1, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 1, 0, 1, 1)
        self.ASAMemory = QtGui.QSpinBox(self.groupBox_3)
        self.ASAMemory.setEnabled(True)
        self.ASAMemory.setMinimum(1)
        self.ASAMemory.setMaximum(100000)
        self.ASAMemory.setSingleStep(16)
        self.ASAMemory.setProperty(_fromUtf8("value"), 256)
        self.ASAMemory.setObjectName(_fromUtf8("ASAMemory"))
        self.gridLayout_3.addWidget(self.ASAMemory, 1, 1, 1, 1)
        self.label_43 = QtGui.QLabel(self.groupBox_3)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_3.addWidget(self.label_43, 2, 0, 1, 1)
        self.ASANICNb = QtGui.QSpinBox(self.groupBox_3)
        self.ASANICNb.setMinimum(0)
        self.ASANICNb.setMaximum(100000)
        self.ASANICNb.setSingleStep(1)
        self.ASANICNb.setProperty(_fromUtf8("value"), 6)
        self.ASANICNb.setObjectName(_fromUtf8("ASANICNb"))
        self.gridLayout_3.addWidget(self.ASANICNb, 2, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.ASANIC = QtGui.QComboBox(self.groupBox_3)
        self.ASANIC.setEnabled(True)
        self.ASANIC.setObjectName(_fromUtf8("ASANIC"))
        self.ASANIC.addItem(_fromUtf8(""))
        self.ASANIC.addItem(_fromUtf8(""))
        self.ASANIC.addItem(_fromUtf8(""))
        self.ASANIC.addItem(_fromUtf8(""))
        self.ASANIC.addItem(_fromUtf8(""))
        self.ASANIC.addItem(_fromUtf8(""))
        self.ASANIC.addItem(_fromUtf8(""))
        self.ASANIC.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.ASANIC, 3, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 4, 0, 1, 1)
        self.ASAOptions = QtGui.QLineEdit(self.groupBox_3)
        self.ASAOptions.setEnabled(True)
        self.ASAOptions.setObjectName(_fromUtf8("ASAOptions"))
        self.gridLayout_3.addWidget(self.ASAOptions, 4, 1, 1, 1)
        self.ASAcheckBoxKqemu = QtGui.QCheckBox(self.groupBox_3)
        self.ASAcheckBoxKqemu.setEnabled(True)
        self.ASAcheckBoxKqemu.setObjectName(_fromUtf8("ASAcheckBoxKqemu"))
        self.gridLayout_3.addWidget(self.ASAcheckBoxKqemu, 5, 0, 1, 1)
        self.ASAcheckBoxKVM = QtGui.QCheckBox(self.groupBox_3)
        self.ASAcheckBoxKVM.setEnabled(True)
        self.ASAcheckBoxKVM.setObjectName(_fromUtf8("ASAcheckBoxKVM"))
        self.gridLayout_3.addWidget(self.ASAcheckBoxKVM, 6, 0, 1, 2)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.ASAInitrd_Browser = QtGui.QToolButton(self.groupBox_4)
        self.ASAInitrd_Browser.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.ASAInitrd_Browser.setObjectName(_fromUtf8("ASAInitrd_Browser"))
        self.gridLayout_4.addWidget(self.ASAInitrd_Browser, 0, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 1, 0, 1, 1)
        self.ASAKernel = QtGui.QLineEdit(self.groupBox_4)
        self.ASAKernel.setObjectName(_fromUtf8("ASAKernel"))
        self.gridLayout_4.addWidget(self.ASAKernel, 1, 1, 1, 1)
        self.ASAKernel_Browser = QtGui.QToolButton(self.groupBox_4)
        self.ASAKernel_Browser.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.ASAKernel_Browser.setObjectName(_fromUtf8("ASAKernel_Browser"))
        self.gridLayout_4.addWidget(self.ASAKernel_Browser, 1, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_4.addWidget(self.label_13, 2, 0, 1, 1)
        self.ASAKernelCmdLine = QtGui.QLineEdit(self.groupBox_4)
        self.ASAKernelCmdLine.setObjectName(_fromUtf8("ASAKernelCmdLine"))
        self.gridLayout_4.addWidget(self.ASAKernelCmdLine, 2, 1, 1, 2)
        self.ASAInitrd = QtGui.QLineEdit(self.groupBox_4)
        self.ASAInitrd.setObjectName(_fromUtf8("ASAInitrd"))
        self.gridLayout_4.addWidget(self.ASAInitrd, 0, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_4.addWidget(self.label_19, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.SaveASAImage = QtGui.QPushButton(self.scrollAreaWidgetContents_4)
        self.SaveASAImage.setObjectName(_fromUtf8("SaveASAImage"))
        self.horizontalLayout_4.addWidget(self.SaveASAImage)
        self.DeleteASAImage = QtGui.QPushButton(self.scrollAreaWidgetContents_4)
        self.DeleteASAImage.setObjectName(_fromUtf8("DeleteASAImage"))
        self.horizontalLayout_4.addWidget(self.DeleteASAImage)
        spacerItem5 = QtGui.QSpacerItem(217, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.groupBox_12 = QtGui.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.treeWidgetASAImages = QtGui.QTreeWidget(self.groupBox_12)
        self.treeWidgetASAImages.setObjectName(_fromUtf8("treeWidgetASAImages"))
        self.verticalLayout_13.addWidget(self.treeWidgetASAImages)
        self.verticalLayout_3.addWidget(self.groupBox_12)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_14.addWidget(self.scrollArea_4)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName(_fromUtf8("tab_6"))
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.tab_6)
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.scrollArea_5 = QtGui.QScrollArea(self.tab_6)
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName(_fromUtf8("scrollArea_5"))
        self.scrollAreaWidgetContents_5 = QtGui.QWidget(self.scrollArea_5)
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 437, 507))
        self.scrollAreaWidgetContents_5.setObjectName(_fromUtf8("scrollAreaWidgetContents_5"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_5)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.groupBox_9 = QtGui.QGroupBox(self.scrollAreaWidgetContents_5)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_45 = QtGui.QLabel(self.groupBox_9)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_8.addWidget(self.label_45, 0, 0, 1, 1)
        self.NameIDSImage = QtGui.QLineEdit(self.groupBox_9)
        self.NameIDSImage.setObjectName(_fromUtf8("NameIDSImage"))
        self.gridLayout_8.addWidget(self.NameIDSImage, 0, 1, 1, 2)
        self.label_27 = QtGui.QLabel(self.groupBox_9)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_8.addWidget(self.label_27, 1, 0, 1, 1)
        self.IDSImage1 = QtGui.QLineEdit(self.groupBox_9)
        self.IDSImage1.setEnabled(True)
        self.IDSImage1.setObjectName(_fromUtf8("IDSImage1"))
        self.gridLayout_8.addWidget(self.IDSImage1, 1, 1, 1, 1)
        self.IDSImage1_Browser = QtGui.QToolButton(self.groupBox_9)
        self.IDSImage1_Browser.setEnabled(True)
        self.IDSImage1_Browser.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.IDSImage1_Browser.setObjectName(_fromUtf8("IDSImage1_Browser"))
        self.gridLayout_8.addWidget(self.IDSImage1_Browser, 1, 2, 1, 1)
        self.label_34 = QtGui.QLabel(self.groupBox_9)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_8.addWidget(self.label_34, 2, 0, 1, 1)
        self.IDSImage2 = QtGui.QLineEdit(self.groupBox_9)
        self.IDSImage2.setEnabled(True)
        self.IDSImage2.setObjectName(_fromUtf8("IDSImage2"))
        self.gridLayout_8.addWidget(self.IDSImage2, 2, 1, 1, 1)
        self.IDSImage2_Browser = QtGui.QToolButton(self.groupBox_9)
        self.IDSImage2_Browser.setEnabled(True)
        self.IDSImage2_Browser.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        self.IDSImage2_Browser.setObjectName(_fromUtf8("IDSImage2_Browser"))
        self.gridLayout_8.addWidget(self.IDSImage2_Browser, 2, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_9)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_8.addWidget(self.label_28, 3, 0, 1, 1)
        self.IDSMemory = QtGui.QSpinBox(self.groupBox_9)
        self.IDSMemory.setEnabled(True)
        self.IDSMemory.setMinimum(1)
        self.IDSMemory.setMaximum(100000)
        self.IDSMemory.setSingleStep(16)
        self.IDSMemory.setProperty(_fromUtf8("value"), 512)
        self.IDSMemory.setObjectName(_fromUtf8("IDSMemory"))
        self.gridLayout_8.addWidget(self.IDSMemory, 3, 1, 1, 2)
        self.label_44 = QtGui.QLabel(self.groupBox_9)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_8.addWidget(self.label_44, 4, 0, 1, 1)
        self.IDSNICNb = QtGui.QSpinBox(self.groupBox_9)
        self.IDSNICNb.setMinimum(0)
        self.IDSNICNb.setMaximum(100000)
        self.IDSNICNb.setSingleStep(1)
        self.IDSNICNb.setProperty(_fromUtf8("value"), 3)
        self.IDSNICNb.setObjectName(_fromUtf8("IDSNICNb"))
        self.gridLayout_8.addWidget(self.IDSNICNb, 4, 1, 1, 2)
        self.label_32 = QtGui.QLabel(self.groupBox_9)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.gridLayout_8.addWidget(self.label_32, 5, 0, 1, 1)
        self.IDSNIC = QtGui.QComboBox(self.groupBox_9)
        self.IDSNIC.setEnabled(True)
        self.IDSNIC.setObjectName(_fromUtf8("IDSNIC"))
        self.IDSNIC.addItem(_fromUtf8(""))
        self.IDSNIC.addItem(_fromUtf8(""))
        self.IDSNIC.addItem(_fromUtf8(""))
        self.IDSNIC.addItem(_fromUtf8(""))
        self.IDSNIC.addItem(_fromUtf8(""))
        self.IDSNIC.addItem(_fromUtf8(""))
        self.IDSNIC.addItem(_fromUtf8(""))
        self.IDSNIC.addItem(_fromUtf8(""))
        self.gridLayout_8.addWidget(self.IDSNIC, 5, 1, 1, 2)
        self.label_33 = QtGui.QLabel(self.groupBox_9)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.gridLayout_8.addWidget(self.label_33, 6, 0, 1, 1)
        self.IDSOptions = QtGui.QLineEdit(self.groupBox_9)
        self.IDSOptions.setEnabled(True)
        self.IDSOptions.setObjectName(_fromUtf8("IDSOptions"))
        self.gridLayout_8.addWidget(self.IDSOptions, 6, 1, 1, 2)
        self.IDScheckBoxKqemu = QtGui.QCheckBox(self.groupBox_9)
        self.IDScheckBoxKqemu.setEnabled(True)
        self.IDScheckBoxKqemu.setObjectName(_fromUtf8("IDScheckBoxKqemu"))
        self.gridLayout_8.addWidget(self.IDScheckBoxKqemu, 7, 0, 1, 1)
        self.IDScheckBoxKVM = QtGui.QCheckBox(self.groupBox_9)
        self.IDScheckBoxKVM.setEnabled(True)
        self.IDScheckBoxKVM.setObjectName(_fromUtf8("IDScheckBoxKVM"))
        self.gridLayout_8.addWidget(self.IDScheckBoxKVM, 8, 0, 1, 2)
        self.verticalLayout_8.addWidget(self.groupBox_9)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.SaveIDSImage = QtGui.QPushButton(self.scrollAreaWidgetContents_5)
        self.SaveIDSImage.setObjectName(_fromUtf8("SaveIDSImage"))
        self.horizontalLayout_5.addWidget(self.SaveIDSImage)
        self.DeleteIDSImage = QtGui.QPushButton(self.scrollAreaWidgetContents_5)
        self.DeleteIDSImage.setObjectName(_fromUtf8("DeleteIDSImage"))
        self.horizontalLayout_5.addWidget(self.DeleteIDSImage)
        spacerItem6 = QtGui.QSpacerItem(217, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.groupBox_13 = QtGui.QGroupBox(self.scrollAreaWidgetContents_5)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.groupBox_13)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.treeWidgetIDSImages = QtGui.QTreeWidget(self.groupBox_13)
        self.treeWidgetIDSImages.setObjectName(_fromUtf8("treeWidgetIDSImages"))
        self.verticalLayout_15.addWidget(self.treeWidgetIDSImages)
        self.verticalLayout_8.addWidget(self.groupBox_13)
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayout_16.addWidget(self.scrollArea_5)
        self.tabWidget.addTab(self.tab_6, _fromUtf8(""))
        self.verticalLayout_17.addWidget(self.tabWidget)

        self.retranslateUi(PreferencesQemu)
        self.tabWidget.setCurrentIndex(0)
        self.QemuNIC.setCurrentIndex(5)
        self.PIXNIC.setCurrentIndex(5)
        self.JunOSNIC.setCurrentIndex(5)
        self.ASANIC.setCurrentIndex(5)
        self.IDSNIC.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(PreferencesQemu)

    def retranslateUi(self, PreferencesQemu):
        PreferencesQemu.setWindowTitle(QtGui.QApplication.translate("PreferencesQemu", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.P.setTitle(QtGui.QApplication.translate("PreferencesQemu", "Qemuwrapper", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("PreferencesQemu", "Path to Qemuwrapper:", None, QtGui.QApplication.UnicodeUTF8))
        self.QemuwrapperPath_browser.setText(QtGui.QApplication.translate("PreferencesQemu", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("PreferencesQemu", "Working directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.QemuwrapperWorkdir_browser.setText(QtGui.QApplication.translate("PreferencesQemu", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("PreferencesQemu", "Path to qemu:", None, QtGui.QApplication.UnicodeUTF8))
        self.QemuPath_browser.setText(QtGui.QApplication.translate("PreferencesQemu", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("PreferencesQemu", "Path to qemu-img:", None, QtGui.QApplication.UnicodeUTF8))
        self.QemuImgPath_browser.setText(QtGui.QApplication.translate("PreferencesQemu", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("PreferencesQemu", "IP/host binding:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("PreferencesQemu", "Qemuwrapper port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("PreferencesQemu", "Base UDP port:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("PreferencesQemu", "Base console port:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxEnableQemuManager.setText(QtGui.QApplication.translate("PreferencesQemu", "Enable Qemu Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxQemuManagerImport.setText(QtGui.QApplication.translate("PreferencesQemu", "Use Qemu Manager when importing", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("PreferencesQemu", "External Qemuwrapper:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonAddExternalQemuwrapper.setText(QtGui.QApplication.translate("PreferencesQemu", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDeleteExternalQemuwrapper.setText(QtGui.QApplication.translate("PreferencesQemu", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("PreferencesQemu", "Registered external Qemuwrappers:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonTestQemu.setText(QtGui.QApplication.translate("PreferencesQemu", "&Test", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("PreferencesQemu", "General Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("PreferencesQemu", "Qemu Host Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("PreferencesQemu", "Identifier name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("PreferencesQemu", "Binary image:", None, QtGui.QApplication.UnicodeUTF8))
        self.QemuImage_Browser.setText(QtGui.QApplication.translate("PreferencesQemu", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("PreferencesQemu", "RAM:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("PreferencesQemu", "Number of NICs:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("PreferencesQemu", "NIC model:", None, QtGui.QApplication.UnicodeUTF8))
        self.QemuNIC.setItemText(0, QtGui.QApplication.translate("PreferencesQemu", "ne2k_pci", None, QtGui.QApplication.UnicodeUTF8))
        self.QemuNIC.setItemText(1, QtGui.QApplication.translate("PreferencesQemu", "i82551", None, QtGui.QApplication.UnicodeUTF8))
        self.QemuNIC.setItemText(2, QtGui.QApplication.translate("PreferencesQemu", "i82557b", None, QtGui.QApplication.UnicodeUTF8))
        self.QemuNIC.setItemText(3, QtGui.QApplication.translate("PreferencesQemu", "i82559er", None, QtGui.QApplication.UnicodeUTF8))
        self.QemuNIC.setItemText(4, QtGui.QApplication.translate("PreferencesQemu", "rtl8139", None, QtGui.QApplication.UnicodeUTF8))
        self.QemuNIC.setItemText(5, QtGui.QApplication.translate("PreferencesQemu", "e1000", None, QtGui.QApplication.UnicodeUTF8))
        self.QemuNIC.setItemText(6, QtGui.QApplication.translate("PreferencesQemu", "pcnet", None, QtGui.QApplication.UnicodeUTF8))
        self.QemuNIC.setItemText(7, QtGui.QApplication.translate("PreferencesQemu", "virtio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("PreferencesQemu", "Qemu Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.QemucheckBoxKqemu.setText(QtGui.QApplication.translate("PreferencesQemu", "Use KQemu", None, QtGui.QApplication.UnicodeUTF8))
        self.QemucheckBoxKVM.setText(QtGui.QApplication.translate("PreferencesQemu", "Use KVM (Linux Only)", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveQemuImage.setText(QtGui.QApplication.translate("PreferencesQemu", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteQemuImage.setText(QtGui.QApplication.translate("PreferencesQemu", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("PreferencesQemu", "Qemu Host Images", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetQemuImages.headerItem().setText(0, QtGui.QApplication.translate("PreferencesQemu", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetQemuImages.headerItem().setText(1, QtGui.QApplication.translate("PreferencesQemu", "Image path", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("PreferencesQemu", "Qemu Host", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("PreferencesQemu", "PIX Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_38.setText(QtGui.QApplication.translate("PreferencesQemu", "Identifier name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("PreferencesQemu", "Binary image:", None, QtGui.QApplication.UnicodeUTF8))
        self.PIXImage_Browser.setText(QtGui.QApplication.translate("PreferencesQemu", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("PreferencesQemu", "RAM:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_39.setText(QtGui.QApplication.translate("PreferencesQemu", "Number of NICs:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("PreferencesQemu", "NIC model:", None, QtGui.QApplication.UnicodeUTF8))
        self.PIXNIC.setItemText(0, QtGui.QApplication.translate("PreferencesQemu", "ne2k_pci", None, QtGui.QApplication.UnicodeUTF8))
        self.PIXNIC.setItemText(1, QtGui.QApplication.translate("PreferencesQemu", "i82551", None, QtGui.QApplication.UnicodeUTF8))
        self.PIXNIC.setItemText(2, QtGui.QApplication.translate("PreferencesQemu", "i82557b", None, QtGui.QApplication.UnicodeUTF8))
        self.PIXNIC.setItemText(3, QtGui.QApplication.translate("PreferencesQemu", "i82559er", None, QtGui.QApplication.UnicodeUTF8))
        self.PIXNIC.setItemText(4, QtGui.QApplication.translate("PreferencesQemu", "rtl8139", None, QtGui.QApplication.UnicodeUTF8))
        self.PIXNIC.setItemText(5, QtGui.QApplication.translate("PreferencesQemu", "e1000", None, QtGui.QApplication.UnicodeUTF8))
        self.PIXNIC.setItemText(6, QtGui.QApplication.translate("PreferencesQemu", "pcnet", None, QtGui.QApplication.UnicodeUTF8))
        self.PIXNIC.setItemText(7, QtGui.QApplication.translate("PreferencesQemu", "virtio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("PreferencesQemu", "Qemu Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.PIXcheckBoxKqemu.setText(QtGui.QApplication.translate("PreferencesQemu", "Use KQemu", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("PreferencesQemu", "PIX Specific Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("PreferencesQemu", "Key:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("PreferencesQemu", "Serial:", None, QtGui.QApplication.UnicodeUTF8))
        self.SavePIXImage.setText(QtGui.QApplication.translate("PreferencesQemu", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.DeletePIXImage.setText(QtGui.QApplication.translate("PreferencesQemu", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("PreferencesQemu", "PIX Images", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetPIXImages.headerItem().setText(0, QtGui.QApplication.translate("PreferencesQemu", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetPIXImages.headerItem().setText(1, QtGui.QApplication.translate("PreferencesQemu", "Image path", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("PreferencesQemu", "PIX", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("PreferencesQemu", "JunOS Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_40.setText(QtGui.QApplication.translate("PreferencesQemu", "Identifier name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("PreferencesQemu", "Binary image:", None, QtGui.QApplication.UnicodeUTF8))
        self.JunOSImage_Browser.setText(QtGui.QApplication.translate("PreferencesQemu", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("PreferencesQemu", "RAM:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_41.setText(QtGui.QApplication.translate("PreferencesQemu", "Number of NICs:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("PreferencesQemu", "NIC model:", None, QtGui.QApplication.UnicodeUTF8))
        self.JunOSNIC.setItemText(0, QtGui.QApplication.translate("PreferencesQemu", "ne2k_pci", None, QtGui.QApplication.UnicodeUTF8))
        self.JunOSNIC.setItemText(1, QtGui.QApplication.translate("PreferencesQemu", "i82551", None, QtGui.QApplication.UnicodeUTF8))
        self.JunOSNIC.setItemText(2, QtGui.QApplication.translate("PreferencesQemu", "i82557b", None, QtGui.QApplication.UnicodeUTF8))
        self.JunOSNIC.setItemText(3, QtGui.QApplication.translate("PreferencesQemu", "i82559er", None, QtGui.QApplication.UnicodeUTF8))
        self.JunOSNIC.setItemText(4, QtGui.QApplication.translate("PreferencesQemu", "rtl8139", None, QtGui.QApplication.UnicodeUTF8))
        self.JunOSNIC.setItemText(5, QtGui.QApplication.translate("PreferencesQemu", "e1000", None, QtGui.QApplication.UnicodeUTF8))
        self.JunOSNIC.setItemText(6, QtGui.QApplication.translate("PreferencesQemu", "pcnet", None, QtGui.QApplication.UnicodeUTF8))
        self.JunOSNIC.setItemText(7, QtGui.QApplication.translate("PreferencesQemu", "virtio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("PreferencesQemu", "Qemu Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.JunOScheckBoxKqemu.setText(QtGui.QApplication.translate("PreferencesQemu", "Use KQemu", None, QtGui.QApplication.UnicodeUTF8))
        self.JunOScheckBoxKVM.setText(QtGui.QApplication.translate("PreferencesQemu", "Use KVM (Linux Only)", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveJunOSImage.setText(QtGui.QApplication.translate("PreferencesQemu", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteJunOSImage.setText(QtGui.QApplication.translate("PreferencesQemu", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_11.setTitle(QtGui.QApplication.translate("PreferencesQemu", "JunOS Images", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetJunOSImages.headerItem().setText(0, QtGui.QApplication.translate("PreferencesQemu", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetJunOSImages.headerItem().setText(1, QtGui.QApplication.translate("PreferencesQemu", "Image path", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("PreferencesQemu", "JunOS", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("PreferencesQemu", "ASA Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_42.setText(QtGui.QApplication.translate("PreferencesQemu", "Identifier name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("PreferencesQemu", "RAM:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_43.setText(QtGui.QApplication.translate("PreferencesQemu", "Number of NICs:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("PreferencesQemu", "NIC model:", None, QtGui.QApplication.UnicodeUTF8))
        self.ASANIC.setItemText(0, QtGui.QApplication.translate("PreferencesQemu", "ne2k_pci", None, QtGui.QApplication.UnicodeUTF8))
        self.ASANIC.setItemText(1, QtGui.QApplication.translate("PreferencesQemu", "i82551", None, QtGui.QApplication.UnicodeUTF8))
        self.ASANIC.setItemText(2, QtGui.QApplication.translate("PreferencesQemu", "i82557b", None, QtGui.QApplication.UnicodeUTF8))
        self.ASANIC.setItemText(3, QtGui.QApplication.translate("PreferencesQemu", "i82559er", None, QtGui.QApplication.UnicodeUTF8))
        self.ASANIC.setItemText(4, QtGui.QApplication.translate("PreferencesQemu", "rtl8139", None, QtGui.QApplication.UnicodeUTF8))
        self.ASANIC.setItemText(5, QtGui.QApplication.translate("PreferencesQemu", "e1000", None, QtGui.QApplication.UnicodeUTF8))
        self.ASANIC.setItemText(6, QtGui.QApplication.translate("PreferencesQemu", "pcnet", None, QtGui.QApplication.UnicodeUTF8))
        self.ASANIC.setItemText(7, QtGui.QApplication.translate("PreferencesQemu", "virtio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("PreferencesQemu", "Qemu Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.ASAcheckBoxKqemu.setText(QtGui.QApplication.translate("PreferencesQemu", "Use KQemu", None, QtGui.QApplication.UnicodeUTF8))
        self.ASAcheckBoxKVM.setText(QtGui.QApplication.translate("PreferencesQemu", "Use KVM (Linux Only)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("PreferencesQemu", "ASA Specific Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.ASAInitrd_Browser.setText(QtGui.QApplication.translate("PreferencesQemu", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("PreferencesQemu", "Kernel:", None, QtGui.QApplication.UnicodeUTF8))
        self.ASAKernel_Browser.setText(QtGui.QApplication.translate("PreferencesQemu", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("PreferencesQemu", "Kernel cmd line:", None, QtGui.QApplication.UnicodeUTF8))
        self.ASAKernelCmdLine.setText(QtGui.QApplication.translate("PreferencesQemu", "console=ttyS0,9600n8 bigphysarea=16384 auto nousb ide1=noprobe hda=980,16,32", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("PreferencesQemu", "Initrd:", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveASAImage.setText(QtGui.QApplication.translate("PreferencesQemu", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteASAImage.setText(QtGui.QApplication.translate("PreferencesQemu", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("PreferencesQemu", "ASA Images", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetASAImages.headerItem().setText(0, QtGui.QApplication.translate("PreferencesQemu", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetASAImages.headerItem().setText(1, QtGui.QApplication.translate("PreferencesQemu", "Initrd path", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetASAImages.headerItem().setText(2, QtGui.QApplication.translate("PreferencesQemu", "Kernel path", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("PreferencesQemu", "ASA", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("PreferencesQemu", "IDS Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label_45.setText(QtGui.QApplication.translate("PreferencesQemu", "Identifier name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("PreferencesQemu", "Binary image 1 (hda):", None, QtGui.QApplication.UnicodeUTF8))
        self.IDSImage1_Browser.setText(QtGui.QApplication.translate("PreferencesQemu", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("PreferencesQemu", "Binary image 2 (hdb):", None, QtGui.QApplication.UnicodeUTF8))
        self.IDSImage2_Browser.setText(QtGui.QApplication.translate("PreferencesQemu", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("PreferencesQemu", "RAM:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_44.setText(QtGui.QApplication.translate("PreferencesQemu", "Number of NICs:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("PreferencesQemu", "NIC model:", None, QtGui.QApplication.UnicodeUTF8))
        self.IDSNIC.setItemText(0, QtGui.QApplication.translate("PreferencesQemu", "ne2k_pci", None, QtGui.QApplication.UnicodeUTF8))
        self.IDSNIC.setItemText(1, QtGui.QApplication.translate("PreferencesQemu", "i82551", None, QtGui.QApplication.UnicodeUTF8))
        self.IDSNIC.setItemText(2, QtGui.QApplication.translate("PreferencesQemu", "i82557b", None, QtGui.QApplication.UnicodeUTF8))
        self.IDSNIC.setItemText(3, QtGui.QApplication.translate("PreferencesQemu", "i82559er", None, QtGui.QApplication.UnicodeUTF8))
        self.IDSNIC.setItemText(4, QtGui.QApplication.translate("PreferencesQemu", "rtl8139", None, QtGui.QApplication.UnicodeUTF8))
        self.IDSNIC.setItemText(5, QtGui.QApplication.translate("PreferencesQemu", "e1000", None, QtGui.QApplication.UnicodeUTF8))
        self.IDSNIC.setItemText(6, QtGui.QApplication.translate("PreferencesQemu", "pcnet", None, QtGui.QApplication.UnicodeUTF8))
        self.IDSNIC.setItemText(7, QtGui.QApplication.translate("PreferencesQemu", "virtio", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("PreferencesQemu", "Qemu Options:", None, QtGui.QApplication.UnicodeUTF8))
        self.IDSOptions.setText(QtGui.QApplication.translate("PreferencesQemu", "-smbios type=1,product=IDS-4215", None, QtGui.QApplication.UnicodeUTF8))
        self.IDScheckBoxKqemu.setText(QtGui.QApplication.translate("PreferencesQemu", "Use KQemu", None, QtGui.QApplication.UnicodeUTF8))
        self.IDScheckBoxKVM.setText(QtGui.QApplication.translate("PreferencesQemu", "Use KVM (Linux Only)", None, QtGui.QApplication.UnicodeUTF8))
        self.SaveIDSImage.setText(QtGui.QApplication.translate("PreferencesQemu", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.DeleteIDSImage.setText(QtGui.QApplication.translate("PreferencesQemu", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_13.setTitle(QtGui.QApplication.translate("PreferencesQemu", "IDS Images", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetIDSImages.headerItem().setText(0, QtGui.QApplication.translate("PreferencesQemu", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetIDSImages.headerItem().setText(1, QtGui.QApplication.translate("PreferencesQemu", "Image 1 path", None, QtGui.QApplication.UnicodeUTF8))
        self.treeWidgetIDSImages.headerItem().setText(2, QtGui.QApplication.translate("PreferencesQemu", "Image 2 path", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("PreferencesQemu", "IDS", None, QtGui.QApplication.UnicodeUTF8))

