.TH "gns3" "1"
.SH "NAME"
gns3 \- a graphical network simulator
.SH "SYNOPSIS"
\fBgns3
.SH "DESCRIPTION"
.B gns3
GNS-3 is a graphical network simulator that allows you to design complex
network topologies. You may run simulations or configure devices ranging from
simple workstations to powerful Cisco routers. It is based on NS-3, a
discrete-event network simulator for Internet systems, and Dynamips, an IOS
emulator which allows users to run IOS binary images from Cisco Systems.
.SH REPORTING BUGS
.br
Please send bug reports to http://www.gns.net/trac
.SH SEE ALSO
.br
.UR
http://www.gns3.net/
.UE
.SH "AUTHOR"
gns3 was written by Jeremy Grossmann, David Ruiz, Romain Lamaison, Aurelien
Levesque and Xavier Alt. The developer can be reached by Email:
contact@gns3.net This manual page was written by Erik Wenzel <erik@debian.org>
for the \fBDebian GNU/Linux\fP system (but may be used by others).

